theme: jekyll-theme-leap-day

title: aki's right brain
description: Leap Day is a theme for GitHub Pages.
show_downloads: true

languages: "ja"
google_analytics: UA-34399144-3
google_tagManager: GTM-PBFKXB5
source: .
# layouts_dir: _layouts
# data_dir: _data # なぜかこのディレクトリをいったん指定しないと _posts が動かなかった
# includes_dir: _includes
# http://jekyllrb-ja.github.io/docs/permalinks/
# permalink: pretty #拡張子を外す
# permalink: /:categories/:year/:month/:day/:title:output_ext
permalink: /:year/:month/:title/
show_excerpts: true # 投稿の中身を展開する
paginate: 5
paginate_path: "/blog/page:num/"
# permalink: date # 不明
# collections_dir: .
collections:
  posts: 
    output: true
plugins:
  - jekyll-paginate

